base_dir = os.path.dirname(os.path.abspath(__file__))
# print("base_dir = ", base_dir)
# imagem_path = os.path.join(base_dir, "Calculadora_Imagem", "num_3.png")
# print("imagem_path = ", imagem_path)
# num3 = pyautogui.locateCenterOnScreen(imagem_path,confidence=0.9)
# print(num3)